name: April Fools

on: [push]

jobs:
  print:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository code
        uses: actions/checkout@v4
      - name: April fools prank
        run: sed -i "s/h1/h3/g" index.html
      - name: Add comment
        run: echo "<!-- Get back to work slave -->" >> index.html